import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import HighlightText from "~/components/HighlightText";
import Footer from "~/components/Footer";
import { useRouter } from 'next/router'
import { api } from "~/utils/api";
import Link from "next/link";
import { useState } from "react";
import EventDescription from "~/module/events/components/EventDescription"
import { SwishQR } from "~/components/SwishQR/SwishQR"


const Home: NextPage = () => {
    //const hello = api.example.hello.useQuery({ text: "from tRPC" });
    const router = useRouter();
    const { eventid } = router.query;
    const { data: sessionData } = useSession();
    //console.log("router.asPath: ", router.asPath)
    //sessionData?.user?.append("name1") = "jw"

    const [attendingToEvent, setAttendToEvent] = useState(false)

    const queryInput = { eventId: eventid as string }
    const event = api.event.getEvent.useQuery(queryInput,
        { enabled: sessionData?.user !== undefined })


    const { mutate: eventSignUp } = api.event.signupForEvent.useMutation()
    const attendToEventHandler = () => {
        //console.log("attendToEventHandler")
        setAttendToEvent(true)
        eventSignUp({ eventId: eventid as string })
    }

    const renderAttending = () => {
        return (
            <div className="grid grid-cols-2  sm:grid-cols-2   gap-4 md:gap-8">
                <div className="col-span-2">
                    <div
                        className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                    >
                        <h3 className="text-2xl font-bold"><HighlightText>Välkommen på Cocktailträff 🎉🍸🍾</HighlightText></h3>
                        <div className="text-lg whitespace-pre-wrap">
                            Kostnaden för träffen är 100:- som ni swishar till 0700066099, märk er betalning med era namn (ex Jonas & Malin).
                            Eller så öppnar ni upp er swish app och skannar QR koden nedan.
                        </div>
                        <div>
                            <SwishQR />
                        </div>
                        <div className="text-lg whitespace-pre-wrap">
                            Efter betalningen så kommer vi lägga till er till träffen och ni kan då se vilka andra som har anmält sig.
                        </div>

                        <div className="text-lg whitespace-pre-wrap">
                            Vi kommer att maila ut mer info några dagar innan träffen. Då berättar vi vilket ställe vi ska ses på. Håll utkik i er mailkorg.
                        </div>

                    </div>
                </div>
            </div>)
    }

    if (event.isLoading || false) {
        return <p>laddar träff...</p>
    }

    if (!event.data) {
        return <p>hittar ingen träff...</p>
    }

    const e = event.data


    return (
        <>
            <Head>
                <title>Night of Passion</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
                        Träff med <HighlightText>Night of Passion</HighlightText>
                    </h1>

                    <EventDescription event={e} />
                    <div className="flex flex-col items-center justify-center gap-4">
                        <div className="flex flex-wrap justify-center justify-self-center">
                            <div className="p-2" >
                                <Link href={router.asPath + "/attendes"}>
                                    <button
                                        className="rounded-full bg-white/10 bg-[hsl(280,100%,70%)] px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">
                                        Vilka kommer på träffen?
                                    </button>
                                </Link>
                            </div>
                            <div className="p-2" >

                                <button
                                    onClick={() => attendToEventHandler()}
                                    className="rounded-full bg-[hsl(280,100%,70%)] px-10 py-3 font-semibold text-white no-underline transition hover:bg-opacity-75">
                                    Anmäl er till träffen
                                </button>
                            </div>
                            {/* {BUTTONS.map(button => renderButton(button))} */}
                        </div>
                    </div>
                    {attendingToEvent ? renderAttending() : null}
                    <div className="flex flex-col items-center gap-2">
                        <Footer />
                    </div>
                </div>
            </main>
        </>
    );
};


export default Home;

