import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { SubmitHandler, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {ProfileSchema} from "~/utils/validation/profile";
import { useEffect } from "react";
import { Profile } from "@prisma/client";

const EditProfilePage: NextPage = () => {
  const utils = api.useContext();
  const myProfile = api.profile.getMyProfile.useQuery();
  const mutation = api.profile.upsertProfile.useMutation();

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<Profile>({
    resolver: zodResolver(ProfileSchema),
  });

  useEffect(() => {
    if(myProfile.data) {
      reset(myProfile.data);
    }
    
  }, [myProfile.data, reset]);



  const onSubmit: SubmitHandler<Profile> = (data) => {
    mutation.mutate(data);
  };

  return (
    <>
      <Head>
        <title>NoP Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <form onSubmit= {handleSubmit(onSubmit)}>
            <div className="space-y-12 rounded-md border-b border-gray-900/10 bg-white p-8">
              <div className="border-b border-gray-900/10 pb-12">
                <h2 className="text-base font-semibold leading-7 text-gray-900">
                  Profile
                </h2>
                <p className="mt-1 text-sm leading-6 text-gray-600">
                  This information will be displayed publicly so be careful what
                  you share.
                </p>

                <div className="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                  <div className="sm:col-span-4">
                    <label
                      htmlFor="name"
                      className="block text-sm font-medium leading-6 text-gray-900"
                    >
                      Username
                    </label>
                    <div className="mt-2">
                      <div className="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                        <span className="flex select-none items-center pl-3 text-gray-500 sm:text-sm">
                          nop-social.com/profile/
                        </span>
                        <input
                          type="text"
                          id="name"
                          autoComplete="name"
                          className="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
                          placeholder="janesmith"
                          {...register("name")}
                        />
                      </div>
                    </div>
                  </div>

                  <div className="col-span-full">
                    <label
                      htmlFor="aboutUs"
                      className="block text-sm font-medium leading-6 text-gray-900"
                    >
                      About
                    </label>
                    <div className="mt-2">
                      <textarea
                        id="aboutUs"
                        rows={3}
                        className="block w-full rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:py-1.5 sm:text-sm sm:leading-6"
                        {...register("aboutUs")}
                      ></textarea>
                    </div>
                    <p className="mt-3 text-sm leading-6 text-gray-600">
                      Write a few sentences about yourself.
                    </p>
                  </div>

                  <div className="col-span-full">
                    <label
                      htmlFor="weAreLookingFor"
                      className="block text-sm font-medium leading-6 text-gray-900"
                    >
                      We are looking for
                    </label>
                    <div className="mt-2">
                      <textarea
                        id="weAreLookingFor"
                        rows={3}
                        className="block w-full rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:py-1.5 sm:text-sm sm:leading-6"
                        {...register("weAreLookingFor")}
                      ></textarea>
                    </div>
                    <p className="mt-3 text-sm leading-6 text-gray-600">
                      Write a few sentences about what you are looking for.
                    </p>
                  </div>

                  <div className="sm:col-span-3">
                    <label
                      htmlFor="country"
                      className="block text-sm font-medium leading-6 text-gray-900"
                    >
                      Hemvist
                    </label>
                    <div className="mt-2">
                      <select
                        id="county"
                        autoComplete="county-name"
                        className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                        {...register("county")}
                      >
                        <option value="">----</option>
                        <option value="Blekinge län">Blekinge län</option>
                        <option value="Dalarnas län">Dalarnas län</option>
                        <option value="Gävleborgs län">Gävleborgs län</option>
                        <option value="Gotlands län">Gotlands län</option>
                        <option value="Hallands län">Hallands län</option>
                        <option value="Jämtlands län">Jämtlands län</option>
                        <option value="Jönköpings län">Jönköpings län</option>
                        <option value="Kalmar län">Kalmar län</option>
                        <option value="Kronobergs län">Kronobergs län</option>
                        <option value="Norrbottens län">Norrbottens län</option>
                        <option value="Skåne län">Skåne län</option>
                        <option value="Södermanlands län">
                          Södermanlands län
                        </option>
                        <option value="Stockholms län">Stockholms län</option>
                        <option value="Uppsala län">Uppsala län</option>
                        <option value="Värmlands län">Värmlands län</option>
                        <option value="Västerbottens län">
                          Västerbottens län
                        </option>
                        <option value="Västernorrlands län">
                          Västernorrlands län
                        </option>
                        <option value="Västmanlands län">
                          Västmanlands län
                        </option>
                        <option value="Västra Götalands län">
                          Västra Götalands län
                        </option>
                        <option value="Örebro län">Örebro län</option>
                        <option value="Östergötlands län">
                          Östergötlands län
                        </option>
                        <option value="Hemlig ort">Hemlig ort</option>
                        <option value="Danmark">Danmark</option>
                        <option value="Finland">Finland</option>
                        <option value="Norge">Norge</option>
                        <option value="Spanien">Spanien</option>
                        <option value="Utomlands">Utomlands</option>
                      </select>
                    </div>
                  </div>

                  <div className="sm:col-span-3">
                    <label
                      htmlFor="city"
                      className="block text-sm font-medium leading-6 text-gray-900"
                    >
                      Stad
                    </label>
                    <div className="mt-2">
                      <input
                        type="text"
                        id="city"
                        autoComplete="city"
                        className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        {...register("city")}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="border-b border-gray-900/10 pb-12">
                <h2 className="text-base font-semibold leading-7 text-gray-900">
                  Om henne
                </h2>
                <p className="mt-1 text-sm leading-6 text-gray-600">
                  Fyll information om henne.
                </p>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Födelseår
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      {[...Array(100).keys()].map((i) => {
                        const year = new Date().getFullYear() -20 - i;
                        return (
                          <option key={year} value={year}>
                            {year}
                          </option>
                        );
                      })}
                    </select>
                  </div>
                </div>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Födelsemånad
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="18-25">Januari</option>
                      <option value="26-30">Feburari</option>
                      <option value="31-35">Mars</option>
                      <option value="36-40">April</option>
                      <option value="41-45">Maj</option>
                      <option value="46-50">Juni</option>
                      <option value="51-55">Juli</option>
                      <option value="56-60">Augusi</option>
                      <option value="61-65">September</option>
                      <option value="65+">Oktober</option>
                      <option value="65+">November</option>
                      <option value="65+">December</option>
                    </select>
                  </div>
                </div>
                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Längd
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="-150 cm">-150 cm</option>
                      <option value="150-159 cm">150-159 cm</option>
                      <option value="160-164 cm">160-164 cm</option>
                      <option value="165-169 cm">165-169 cm</option>
                      <option value="170-174 cm">170-174 cm</option>
                      <option value="175-179 cm">175-179 cm</option>
                      <option value="180-185 cm">180-185 cm</option>
                      <option value="186-190 cm">186-190 cm</option>
                      <option value="191-199 cm">191-199 cm</option>
                      <option value="200 cm eller längre">
                        200 cm eller längre
                      </option>
                    </select>
                  </div>
                </div>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Läggning
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="Heterosexuell">Heterosexuell</option>
                      <option value="Binyfiken">Binyfiken</option>
                      <option value="Bisexuell">Bisexuell</option>
                      <option value="Homosexuell">Homosexuell</option>
                      <option value="Experimentell">Experimentell</option>
                      <option value="Annat">Annat</option>
                    </select>
                  </div>
                </div>
              </div>

              <div className="border-b border-gray-900/10 pb-12">
                <h2 className="text-base font-semibold leading-7 text-gray-900">
                  Om honom
                </h2>
                <p className="mt-1 text-sm leading-6 text-gray-600">
                  Fyll i information om honom.
                </p>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Födelseår
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      {[...Array(100).keys()].map((i) => {
                        const year = new Date().getFullYear() -20 - i;
                        return (
                          <option key={year} value={year}>
                            {year}
                          </option>
                        );
                      })}
                    </select>
                  </div>
                </div>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Födelsemånad
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="18-25">Januari</option>
                      <option value="26-30">Feburari</option>
                      <option value="31-35">Mars</option>
                      <option value="36-40">April</option>
                      <option value="41-45">Maj</option>
                      <option value="46-50">Juni</option>
                      <option value="51-55">Juli</option>
                      <option value="56-60">Augusi</option>
                      <option value="61-65">September</option>
                      <option value="65+">Oktober</option>
                      <option value="65+">November</option>
                      <option value="65+">December</option>
                    </select>
                  </div>
                </div>
                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Längd
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="-150 cm">-150 cm</option>
                      <option value="150-159 cm">150-159 cm</option>
                      <option value="160-164 cm">160-164 cm</option>
                      <option value="165-169 cm">165-169 cm</option>
                      <option value="170-174 cm">170-174 cm</option>
                      <option value="175-179 cm">175-179 cm</option>
                      <option value="180-185 cm">180-185 cm</option>
                      <option value="186-190 cm">186-190 cm</option>
                      <option value="191-199 cm">191-199 cm</option>
                      <option value="200 cm eller längre">
                        200 cm eller längre
                      </option>
                    </select>
                  </div>
                </div>

                <div className="sm:col-span-3">
                  <label
                    htmlFor="country"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Läggning
                  </label>
                  <div className="mt-2">
                    <select
                      id="country"
                      name="country"
                      autoComplete="country-name"
                      className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                      <option value="">----</option>
                      <option value="Heterosexuell">Heterosexuell</option>
                      <option value="Binyfiken">Binyfiken</option>
                      <option value="Bisexuell">Bisexuell</option>
                      <option value="Homosexuell">Homosexuell</option>
                      <option value="Experimentell">Experimentell</option>
                      <option value="Annat">Annat</option>
                    </select>
                  </div>
                </div>


              </div>






              <div className="mt-6 flex items-center justify-end gap-x-6">
                <button
                  type="button"
                  className="text-sm font-semibold leading-6 text-gray-900"
                >
                  Cancel
                </button>
                {mutation.isSuccess && (<div>Saved!</div>)}
                <button
                  type="submit"
                  className="rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  Save
                </button>
              </div>
            </div>
          </form>

          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default EditProfilePage;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
