import { type NextPage } from "next";
import { useState } from "react"
import Head from "next/head";
import useFirebaseAuth from "../lib/firebase/useFirebaseAuth";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Firebase Auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Firebase <span className="text-[hsl(280,100%,70%)]">Auth</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">

            <FirebaseAuthDemo />


          </div>

        </div>
      </main>
    </>
  );
};

export default Home;

const FirebaseAuthDemo: React.FC = () => {

  const [signinData, setSigninData] = useState({})
  const [signinError, setSigninError] = useState(false)
  const { authUser, loading, signIn, signOut } = useFirebaseAuth()

  const update = (event) => {
    setSigninData((data) => {
      signinData[event.target.name] = event.target.value
      return signinData
    })
  }

  const signOutUser = () => {
    signOut();
    setSigninData({})
  }

  const signInUser = () => {
    setSigninError(false);
    console.log("signinUser: ", signinData)
    const si = signIn(signinData.email, signinData.password)
      .then((authUser) => console.log("signin:", authUser))
      .catch((error) => {
        console.error("failed signin");
        console.error(error.message);
        setSigninError(true);
      });
  }

  return (
    <>
      <h3 className="text-2xl font-bold">FirebaseAuthDemo →</h3>
      <div className="text-lg">UID: <span className="text-">{authUser && authUser.uid || "-"}</span></div>
      <div className="text-lg">Email: <span className="text-">{authUser && authUser.email || "-"}</span></div>

      {authUser &&
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={signOutUser}
        >
          Sign out
        </button>}

      {!authUser && <>
        Email
        <input
          className="rounded-full bg-white px-10 py-3 font-semibold text-[hsl(280,100%,70%)] no-underline transition hover:bg-white/5"
          name="email"
          type="text"
          onChange={update}
        />
        Password
        <input
          className="rounded-full bg-white px-10 py-3 font-semibold text-[hsl(280,100%,70%)] no-underline transition hover:bg-white/5"
          name="password"
          type="password"
          onChange={update}
        />
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={signInUser}
        >
          Sign in
        </button>
        {signinError && <p>Error on signin</p>}</>}

    </>)
}
