import { useRef } from "react"
import Head from "next/head";
import Link from "next/link";
// import { providers, signIn, getSession, csrfToken } from "next-auth/client/";
import { getProviders, signIn } from "next-auth/react"

function Signin({ providers }) {
    console.log("signin: ", providers)
    const inputUsername = useRef(null);
    const inputPassword = useRef("hej123");

    const nopAuthSignIn = (providers) => {
        const nopSigninProvider = Object.values(providers).filter(provider => provider.id == "nop-auth")[0]
        console.log("nopAuthSignIn.nopSigninProvider: ", nopSigninProvider)


        if (!nopSigninProvider) return <div>no nop</div>

        const signinNopAuth = () => {
            console.log("Signin.nopAuthSignIn.signinNopAuth", inputUsername.current, inputPassword)
            console.log("Signin.nopAuthSignIn.signinNopAuth", inputUsername.current.value, inputPassword)
            signIn('nop-auth', { redirect: false, username: inputUsername.current.value, password: inputPassword.current.value })
        }

        return (<><div>nop-signin</div>
            <form className="m-2" >
                <div className="m-2">email</div>
                <input
                    className="m-2 rounded-full"
                    name="username" ref={inputUsername}></input><br />
                <div className="m-2">password</div>
                <input className="m-2 rounded-full"
                    name="password" type="password" ref={inputPassword}></input><br />
                <button
                    className="m-2 rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                    onClick={() => signinNopAuth()}>Signin</button>
            </form></>)
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
                    </h1>
                    <div className="grid grid-cols-1 sm:grid-cols-1 gap-4 md:gap-8">
                        <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">

                            <h3 className="text-2xl font-bold">First Steps →</h3>
                            <div className="text-lg">
                                {nopAuthSignIn(providers)}
                            </div>

                        </div>
                    </div>
                    <div>
                        <Link
                            href="/">
                            <button
                                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                            >
                                Back
                            </button></Link>
                    </div>
                </div>
            </main>
        </>
    );
}

export default Signin;

export async function getServerSideProps() {
    return {
        props: {
            providers: await getProviders(),
        },
    };
}