import { useRef } from "react"
import Head from "next/head";
import Link from "next/link";
// import { providers, signIn, getSession, csrfToken } from "next-auth/client/";
import { getProviders, signIn, signOut, getCsrfToken, getSession, useSession } from "next-auth/react"
import { authOptions } from "./api/auth/[...nextauth]"
import { getServerSession } from "next-auth/next"
import type {
    Provider
} from "next-auth/providers"

function Signin({ providers: Provider[] },) {
    console.log("signin: ", providers)
    const inputUsername = useRef<HTMLInputElement>(null);
    const inputPassword = useRef<HTMLInputElement>(null);

    const nopAuthSignIn = (providers: Provider[]) => {
        const nopSigninProvider = Object.values(providers).filter(provider => provider.id == "nop-auth")[0]
        //console.log("nopAuthSignIn.nopSigninProvider: ", nopSigninProvider)


        if (!nopSigninProvider) return <div>no nop</div>

        const signinNopAuth = async (event: React.FormEvent<HTMLFormElement>) => {
            console.log("Signin.nopAuthSignIn.signinNopAuth.event", event)
            event.preventDefault()
            console.log("Signin.nopAuthSignIn.signinNopAuth", inputUsername.current, inputPassword)
            console.log("Signin.nopAuthSignIn.signinNopAuth", inputUsername.current?.value, inputPassword)
            const signinreturn = await signIn('nop-auth', {
                redirect: true,
                username: inputUsername.current?.value,
                password: inputPassword.current?.value
            })
            console.log("--------------------Signin.nopAuthSignIn.signinNopAuth.signinreturn", signinreturn)
        }

        return (
            <>
                <form className="p-2" >
                    <div className="m-2">email</div>
                    <input
                        className="w-full px-3 py-3 rounded-full text-black text-center"
                        name="username" ref={inputUsername}></input><br />
                    <div className="m-2">password</div>
                    <input className="w-full px-3 py-3 rounded-full text-black text-center"
                        name="password" type="password" ref={inputPassword}></input><br />
                    <button
                        className="m-2 rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                        onClick={(event) => signinNopAuth(event)}>Signin</button>
                </form>
            </>
        )
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Signin to <span className="text-[hsl(280,100%,70%)]">Night of Passion</span>
                    </h1>
                    <div className="grid w-full xl:w-1/2 grid-cols-1 sm:grid-cols-1 gap-4 md:gap-8">
                        <div className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">

                            <h3 className="text-2xl font-bold">Signin →</h3>
                            <div className="text-lg">
                                {nopAuthSignIn(providers)}
                            </div>

                        </div>
                    </div>
                    <div>
                        <Link
                            href="/">
                            <button
                                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                            >
                                Back
                            </button></Link>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                        <AuthShowcase />
                    </div>
                </div>
            </main>
        </>
    );
}

const AuthShowcase: React.FC = () => {
    const { data: sessionData } = useSession();



    console.log("AuthShowcase.sessionData", sessionData)
    return (
        <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white">
                {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
            </p>
            <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
                {sessionData ? "Sign out" : "Sign in"}
            </button>
        </div>
    );
};
export default Signin;

export async function getServerSideProps(context) {

    const session = await getServerSession(context.req, context.res, authOptions)

    if (session) {
        return {
            redirect: { destination: "/" },
        };
    }

    return {
        props: {
            providers: await getProviders(),
            csrfToken: await getCsrfToken(),
        },
    };
}