import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import HighlightText from "~/components/HighlightText";
import SigninButton from "~/components/SigninButton";
import { useRouter } from 'next/router'
import { api } from "~/utils/api";
import Link from "next/link";
import { useState } from "react";
import Image from 'next/image'
import swishPic from './swish.png'


const Home: NextPage = () => {
    //const hello = api.example.hello.useQuery({ text: "from tRPC" });
    const router = useRouter();
    const { eventid } = router.query;
    const { data: sessionData } = useSession();
    const [attendingToEvent, setAttendToEvent] = useState(false)

    const queryInput = { eventId: eventid as string }
    const event = api.event.getEvent.useQuery(queryInput,
        { enabled: sessionData?.user !== undefined })


    const attendToEventHandler = () => {
        console.log("attendToEventHandler")
        setAttendToEvent(true)

    }

    const renderAttending = () => {
        return (
            <div className="grid grid-cols-2  sm:grid-cols-2   gap-4 md:gap-8">
                <div className="col-span-2">
                    <div
                        className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                    >
                        <h3 className="text-2xl font-bold"><HighlightText>Välkommen på Cocktailträff 🎉🍸🍾</HighlightText></h3>
                        <div className="text-lg whitespace-pre-wrap">
                            Kostnaden för träffen är 100:- som ni swishar till 0700066099, märk er betalning med era namm (XX & YY)
                            Eller så öppnar ni upp er swish app och skannar QR koden nedan.
                        </div>
                        <div>
                            <Image
                                className="m-auto"
                                src={swishPic}
                                alt="Swish QR för träffen"
                                width={500}
                                height={500}
                            // blurDataURL="data:..." automatically provided
                            // placeholder="blur" // Optional blur-up while loading
                            />
                        </div>
                        <div className="text-lg whitespace-pre-wrap">
                            Efter betalningen så kommer vi lägga till er till träffen och ni kan då få se vilka andra som har anält sig. Vi kommer att skicka ut mer info om träffen några dagar innan.
                        </div>
                    </div>
                </div>
            </div>)
    }

    if (event.isLoading || false) {
        return <p>laddar träff...</p>
    }

    if (!event.data) {
        return <p>hittar ingen träff...</p>
    }

    const e = event.data


    return (
        <>
            <Head>
                <title>Night of Passion</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
                        Träff med <HighlightText>Night of Passion</HighlightText>
                    </h1>

                    <div className="grid grid-cols-2  sm:grid-cols-2   gap-4 md:gap-8">
                        <div className="col-span-2">
                            <div
                                className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            >
                                <h3 className="text-2xl font-bold"><HighlightText>{e.title}</HighlightText></h3>
                                <div className="text-lg whitespace-pre-wrap">
                                    {e.when}
                                </div>
                                <div className="text-lg whitespace-pre-wrap">
                                    {e.longDesc}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="flex flex-col items-center justify-center gap-4">
                        <div className="flex flex-wrap justify-center justify-self-center">
                            <div className="p-2" >

                                <button
                                    onClick={() => attendToEventHandler()}
                                    className="rounded-full bg-white/10 bg-[hsl(280,100%,70%)] px-10 py-3 font-semibold text-white no-underline transition hover:bg-[hsl(280,100%,70%)]">
                                    Anmäl er till träffen
                                </button>

                            </div>
                            {/* {BUTTONS.map(button => renderButton(button))} */}
                        </div>
                    </div>
                    {attendingToEvent ? renderAttending() : null}
                    <div className="flex flex-col items-center gap-2">
                        <SigninButton />
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;

