import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SigninButton from "~/components/SigninButton";
import { EVENTS, type Event } from "~/lib/event/events";
import { useRouter } from 'next/router'
import React, { useEffect, useState } from "react";



const Home: NextPage = () => {
    //const hello = api.example.hello.useQuery({ text: "from tRPC" });
    const router = useRouter()
    const [event, setEvent] = useState<Event | undefined>(undefined)
    console.log("eventpage.router.query", router.query)
    console.log("eventpage.router.query.id", router.query.id)
    console.log("eventpage.router.query.slug", router.query.slug)


    useEffect(() => {
        const loadedevent = EVENTS.find(event => event.id == router.query.id)
        if (!loadedevent) {
            void router.push('/app/event/event_not_found')
        }
        setEvent(loadedevent)
    })


    return event ? (
        <>
            <Head>
                <title>Night of Passion</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Event med <span className="text-[hsl(280,100%,70%)]">Night of Passion</span>
                    </h1>

                    <div className="grid grid-cols-2  sm:grid-cols-2   gap-4 md:gap-8">
                        <div className="col-span-2">
                            <div
                                className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            >

                                <h3 className="text-2xl font-bold">{event.title}</h3>
                                <div className="text-lg">
                                    {event.description}
                                </div>

                            </div>
                        </div>

                    </div>
                    <div className="flex flex-col items-center gap-2">
                        <SigninButton />
                    </div>
                </div>
            </main>
        </>
    ) : null;
};

export default Home;

